### ISSUE TITLE
Deprecate in favour of _vates_ pulumi provider

### ISSUE THREAD

**Issue by belfhi** [aslak11/pulumi-xenorchestra#1]
Hi @aslak11,
we have added a repository in the _vatesfr_ github organization and rebuilt the pulumi provider using the boilerplate repository.
Would you be interested in contributing to the vates/pulumi-xenorchestra repo?
Also, we would like to publish an up to date package on pypi.org, could you transfer ownership to _vatesfr_?

**Comment by aslak11** [comment]
The project pulumi-xenorchestra has been deleted.
